service: sls-middy-api

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: us-east-1
  profile: pessoal
  memorySize: 256

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    exclude:
      - "@aws-sdk/*"

functions:
  upload:
    handler: src/main/functions/upload.handler
    events:
      - httpApi:
          path: /upload
          method: POST
  users:
    handler: src/main/functions/users.handler
    events:
      - httpApi:
          path: /users
          method: ANY
      - httpApi:
          path: /users/{param+}
          method: ANY
