service: live055

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: us-east-1
  profile: pessoal
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:PutObject
          Resource:
            - arn:aws:s3:::compressor-test-bucket
            - arn:aws:s3:::compressor-test-bucket/*

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    exclude:
      - "@aws-sdk/*"

functions:
  upload:
    handler: src/main/functions/upload.handler
    events:
      - httpApi:
          path: /upload
          method: POST
  users:
    handler: src/main/functions/users.handler
    events:
      - httpApi:
          path: /users
          method: ANY
      - httpApi:
          path: /users/{param+}
          method: ANY
